stderr of test 'prepare-types.Bug-6724` in directory 'sql/test/BugTracker-2019` itself:


# 11:53:57 >  
# 11:53:57 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=30297" "--set" "mapi_usock=/var/tmp/mtest-26605/.s.monetdb.30297" "--set" "monet_prompt=" "--forcemito" "--dbpath=/home/ferreira/repositories/MonetDB-Apr2019/BUILD/var/MonetDB/mTests_sql_test_BugTracker-2019" "--set" "embedded_c=true"
# 11:53:57 >  

MAPI  = (monetdb) /var/tmp/mtest-3187108/.s.monetdb.30091
QUERY = exec  2(); --error
ERROR = !EXEC called with wrong number of arguments: expected 1, got 0
CODE  = 42000

# 11:53:58 >  
# 11:53:58 >  "Done."
# 11:53:58 >  

